# Generated by Django 5.0.3 on 2024-03-15 10:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("userLogin", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customeusermodel",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelTable(
            name="customeusermodel",
            table="user",
        ),
    ]
