# Generated by Django 5.0.3 on 2024-03-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userLogin", "0002_alter_customeusermodel_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customeusermodel",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Active"), (0, "Inactive"), (-1, "Delete")],
                db_index=True,
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="customeusermodel",
            name="id",
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
